### ISSUE TITLE
send_messages() should return the number of sent messages

### ISSUE THREAD

**Issue by mbi** [digitalvalley-nl/django-mailersend#2]
According to the [Django documentation](https://docs.djangoproject.com/en/4.1/topics/email/#defining-a-custom-email-backend),  `send_messages()` should return the number of sent messagesage. This will then also be used to return an bool from e.g. `django.core.mail.send_mail` indicating whether the message was sent or not. As it is, it'll just return None with this backend.

**Comment by davidconde-nl** [comment]
Thanks for your report. I will investigate the issue.

**Comment by davidconde-nl** [comment]
Fixed in `v0.2.1-alpha`.
